config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root 'gossips#index'

resources :gossips

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
	before_action :set_gossip, only:[:show, :edit, :update, :destroy]

	def index
		@gossips = Gossip.all
	end

	def new
  		@gossip = Gossip.new
	end

	def create
		@gossip = Gossip.new(gossip_params)
		@gossip.save
		redirect_to @gossip
	end

	def gossip_params
		params.require(:gossip).permit(:anonymous_author, :content)
	end

	def show
  		@gossip = Gossip.find(params[:id])
	end

	def edit
	@gossip = Gossip.find(params[:id])
	end 

	def update
  	@gossip = Gossip.find(params[:id])
 	@gossip.update(gossip_params)
    redirect_to @gossip
  	end

  	def destroy
  		@gossip.destroy
  		redirect_to gossips_path
  	end

  	def set_gossip
  		@gossip = Gossip.find(params[:id])
  	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gossips/edit.html.erb
<h1>Edit gossip</h1>
 
<%= form_with(model: @gossip, local: true) do |form| %>
 
  <% if @gossip.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@gossip.errors.count, "error") %> prohibited
        this gossip from being saved:
      </h2>
      <ul>
        <% @gossip.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
 
    <p>
    <%= form.label :anonymous_author %><br>
    <%= form.text_field :anonymous_author %>
  </p>
 
  <p>
    <%= form.label :content %><br>
    <%= form.text_field :content %>
  </p>
 
  <p>  
    <%= form.submit %>
  </p>
 
<% end %>

  <p>
    <%= button_to 'Delete Gossip', @gossip, method: :delete %>
  </p>

<%= link_to 'Back', gossips_path %>

	

app/views/gossips/index.html.erb
<h1>Hello Ladies and Gentlemen !</h1> 
<h2>This website is dedicated to THP gossips</h2>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Anonymous author</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gossips.each do |gossip| %>
      <tr>
      	<td><%= gossip.id %></td>
        <td><%= gossip.anonymous_author %></td>
        <td><%= gossip.content %></td>
        <td><%= link_to 'Show', gossip %></td>
        <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
        <td><%= link_to 'Delete', gossip, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div><%= link_to"New Gossip",new_gossip_path %></div>

app/views/gossips/new.html.erb
<h1> New Gossip </h1>

<%= form_for @gossip do |f| %>
<p><%= f.label :anonymous_author %><br>
   <%= f.text_field :anonymous_author %></p>
 <p><%= f.label :content %><br>
    <%= f.text_field :content %></p>
  <%= f.submit "Create" %>
<% end %>

</br>
<div><%= link_to"Back",root_path %></div>

app/views/gossips/show.html.erb
<h3>Author:</h3>
<p><%= @gossip.anonymous_author %></p>

<h3>Content:</h3>
<p><%= @gossip.content %></p>


<div><%= link_to"Back",root_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>